// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/1/13 16:28:36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/workspace/Git/grugblog/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/workspace/Git/grugblog/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/workspace/Git/grugblog/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/workspace/Git/grugblog/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/workspace/Git/grugblog/frontend/plugins/**/*.{js,ts,mjs}","E:/workspace/Git/grugblog/frontend/composables/**/*.{js,ts,mjs}","E:/workspace/Git/grugblog/frontend/utils/**/*.{js,ts,mjs}","E:/workspace/Git/grugblog/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/workspace/Git/grugblog/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/workspace/Git/grugblog/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/workspace/Git/grugblog/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;